spring.application.name=page-pulse

server.port=${PORT:8080}

server.error.include-stacktrace=never
server.error.include-message=never

# Cache 5 minutes
cache.ttl=300000

# HTTP Timeout
audit.connection-timeout=5
audit.request-timeout=5

